Add validation if CSV data is successfully added in BE, show feedback…
HessianPL/MegaK_HeadHunter_FE pull request #13
Opened 2023-05-01 14:33 UTC by HessianPL

… to the user

2023-05-01 14:40 UTC, HessianPL commented
Sprawdza podczas fetcha potwierdzenie dodania danych na BE. Informuje użytkownika czy się udało czy też nie.

Brak jest implementacji sprawdzenia, czy rozszerzenie pliku jest prawidłowe. Nie wiem jak to zrobić, nie wiem też czy jest potrzebne. Podczas uploadu pliku, w oknie wyboru pliku pojawiają się do wyboru tylko pliki z odpowiednim rozszerzeniem. A jeżeli dane z pliku są nieprawidłowe to i tak nie są przesyłane na BE. Mogę dorzucić w takim wypadku info userowi, ale do obgadania jak to zrobić, bo nie chcę tworzyć kolejnych state'ów - może jakiś komponent który pokazuje userowi błędy? Ale to też nie wiem gdzie go wrzucić, bo nie mamy tego ustalonego (jak i w ogóle całej obsługi błędów).

2023-05-01 17:26 UTC, WeronikaSzemi reviewed
Rzeczywiście nie ma potrzeby sprawdzać rozszerzenia, zostawiłabym to. Natomiast jeżeli dane są niepoprawne i nie zostaną zapisane w bazie, dałabym taką informację.

Zamiast tworzyć nowy stan, można by spróbować zmienić charakter aktualnego. Na przykład można by zapisywać w stanie już samą wiadomość, i byłyby trzy do wyboru: (1) import się udał, (2) import się nie udał, bo nie, i (3) import się nie udał, bo złe dane. Alternatywnie można mieć w stanie jakiekolwiek trzy elementy, enuma jakiegoś, albo boolean i undefined, gdzie false to złe dane, a undefined to nie wyszło, bo nie.

W każdym razie gdzieś w Twojej funkcji jest przecież sprawdzane, czy dane były poprawne, więc jeżeli wyjdzie, że nie (np. przy stringify?), to ustawiasz stan na opcję (3).

ALBO: Od razu w aktualnym kodzie dopisujesz do wiadomości, że nie wyszło, wskazówkę: „Sprawdź, czy format danych jest poprawny”. Mniej admin-friendly, gdyby miał wystąpić błąd w połączeniu z bazą na przykład, ale zawsze jakieś wyjście.

2023-05-01 17:26 UTC, WeronikaSzemi commented on src/components/admin/ImportCSV.tsx
> +                                            : "Wystąpił błąd podczas importu danych Kursantów. Dane nie zostały zaimportowane."
J.w.
```suggestion
                                            : "Wystąpił błąd podczas importu danych. Dane nie zostały zaimportowane."
```

2023-05-01 17:26 UTC, WeronikaSzemi commented on src/components/admin/ImportCSV.tsx
> +                                <p style={{color: "white"}}>{
Ujednolicenie sposobu stylowania.
```suggestion
                                <p className="theme-text-light">{
```

2023-05-02 13:52 UTC, LeneczKa requested changes
Hej, ja nic nie znalazlam więcej. Jak poprawisz zgodnie z uwagami Weroniki to powinno być dobrze.

2023-05-07 19:49 UTC, closed without merging